#!/bin/sh
#!/bin/bash
#Created by FahimAnayet
if [ -z "$2" ]
then
	if [[ "$1" == *".m3u8"* ]]; then
		youtube-dl --verbose --hls-prefer-native --fixup never $1
	else
		youtube-dl -F $1
	fi
	elif [ -z "$4" ]
		then
		      youtube-dl -f $1 $2 --external-downloader aria2c --external-downloader-args "-x $3 -k 1M"
	else
	      youtube-dl -f $1+$2 $3 --external-downloader aria2c --external-downloader-args "-x $4 -k 1M"
fi